### ISSUE TITLE
[BUG] Server crashes when adding AMI

### ISSUE THREAD

**Issue by IIIap** [CrimsonCrips/AlexsMobsInteraction#68]
**Describe the bug**
well, i added AMI (version 5.3) and server crashes
works fine when removing AMI

**Additional context**
logs: https://logs.hosting-minecraft.pro/aloliradul
mod list:
almostunified-forge-1.20.1-0.9.4.jar
alternate_current-mc1.20-1.7.0.jar
AmbientSounds_FORGE_v6.1.6_mc1.20.1.jar
amendments-1.20-1.2.19.jar
appleskin-forge-mc1.20.1-2.5.1.jar
Architects-Palette-1.20.1-1.3.6.1.jar
architectury-9.2.14-forge.jar
AutochefsDelight-1.20.1-Forge-1.0.6.jar
balm-forge-1.20.1-7.3.18-all.jar
bellsandwhistles-0.4.5-1.20.x-Create6.0+.jar
BetterAdvancements-Forge-1.20.1-0.4.2.25.jar
betterfpsdist-1.20.1-6.0.jar
bocchium-1.20.1-0.0.3.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
botarium-forge-1.20.1-2.3.4.jar
BrewinAndChewin-1.20.1-3.2.1.jar
carryon-forge-1.20.1-2.1.2.7.jar
chisels-and-bits-forge-1.4.148.jar
Chunky-1.3.146.jar
citadel-2.6.1-1.20.1 (1).jar
cleanswing-1.20-1.8.jar
clickadv-1.20.1-3.8.jar
Clumps-forge-1.20.1-12.0.0.4.jar
comforts-forge-6.4.0+1.20.1.jar
connectivity-1.20.1-7.1.jar
constantmusic-forge-1.20.1-1.0.5.jar
Controlling-forge-1.20.1-12.0.2.jar
corail_woodcutter-1.20.1-3.0.6 (1).jar
corpse-forge-1.20.1-1.0.20 (1).jar
corpsecurioscompat-1.18.x-1.20.x-Forge-2.2.2.jar
cosmeticarmorreworked-1.20.1-v1a.jar
craftingtweaks-forge-1.20.1-18.2.5.jar
create_compressed-2.1.0-forge-1.20.1.jar
create_enchantment_industry-1.3.2-for-create-6.0.3.jar
create_misc_and_things_ 1.20.1_4.0A.jar
create_oxidized-0.1.2.jar
create_power_loader-2.0.0-mc1.20.1.jar
create_tweaked_controllers-1.20.1-1.2.5.jar
create-1.20.1-6.0.4.jar
create-new-age-forge-1.20.1-1.1.3.jar
CreateNumismatics-1.0.15+forge-mc1.20.1.jar
CreativeCore_FORGE_v2.12.31_mc1.20.1.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.12.1+1.20.1.jar
DarkPaintings-Forge-1.20.1-17.0.4.jar
Delightful-1.20.1-3.7.1.jar
durabilitytooltip-1.1.5-forge-mc1.20.jar
embeddium-0.3.31+mc1.20.1.jar
emi_enchanting-0.1.2+1.20.1+forge.jar
emi_loot-0.7.5+1.20.1+fix1+forge.jar
emi-1.1.20+1.20.1+forge.jar
emiffect-forge-1.1.2+mc1.20.1.jar
emitrades-forge-1.2.1+mc1.20.1.jar
ends_delight-1.20.1-2.4.jar
EpheroLib-1.20.1-FORGE-1.2.0.jar
everycomp-1.20-2.7.23.jar
exposure-1.20.1-1.7.10-forge.jar
extrasounds-1.20.1-forge-1.3 (2).jar
FarmersDelight-1.20.1-1.2.7.jar
FasterLadderClimbing-1.20.1-0.2.10.jar
FastLeafDecay-32.jar
ferritecore-6.0.1-forge.jar
findme-3.2.1-forge.jar
ftbbackups2-forge-1.20-1.0.23 (1).jar
fuelgoeshere-1.20.0-1.0.1 (4).jar
functionalstorage-1.20.1-1.2.10.jar
fzzy_config-0.6.6+1.20.1+forge.jar
Geophilic v3.2 f15-61.jar
grieflogger-1.2.3-1.20.1-forge.jar
handcrafted-forge-1.20.1-3.0.6.jar
ImmediatelyFast-Forge-1.5.0+1.20.4.jar
incontrol-1.20-9.2.11.jar
interiors-0.5.6+forge-mc1.20.1-local.jar
inventoryessentials-forge-1.20.1-8.2.7.jar
Jade-1.20.1-Forge-11.13.1.jar
JadeAddons-1.20.1-Forge-5.5.0.jar
jei-1.20.1-forge-15.20.0.106.jar
kotlinforforge-4.11.0-all.jar
kubejs-create-forge-2001.3.0-build.8.jar
kubejs-forge-2001.6.5-build.16.jar
lmft-1.0.4+1.20.1-forge.jar
logprot-1.20.1-3.5.jar
lootintegrations-1.20.1-4.2.jar
lootjs-forge-1.20.1-2.12.0.jar
lootr-forge-1.20-0.7.35.90.jar
modernfix-forge-5.20.2+mc1.20.1.jar
moonlight-1.20-2.13.75-forge.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
MyNethersDelight-1.20.1-0.1.7.5 (1).jar
NaturesCompass-1.20.1-1.11.2-forge.jar
oceansdelight-1.0.2-1.20.jar
Patchouli-1.20.1-84.1-FORGE.jar
PhilipsRuins1.20.1-5.0.jar
pipeorgans-0.6.1+1.20.1.jar
plushie_buddies-0.1.3-1.20.1.jar
polylib-forge-2000.0.3-build.143 (1).jar
polymorph-forge-0.49.8+1.20.1.jar
probejs-6.0.1-forge.jar
Quark-4.0-461.jar
QuarkOddities-1.20.1.jar
Quit-Forge-1.19.4-1.20.X-1.1.0.jar
RegionsUnexploredForge-0.5.6+1.20.1.jar
resourcefulconfig-forge-1.20.1-2.1.3.jar
resourcefullib-forge-1.20.1-2.1.29.jar
rhino-forge-2001.2.3-build.10.jar
rubidium-extra-0.5.4.4+mc1.20.1-build.131.jar
Searchables-forge-1.20.1-1.0.3.jar
SimpleLogin-1.20.1-1.0.2-all.jar
solcarrot-1.20.1-1.15.1.jar
sophisticatedbackpacks-1.20.1-3.23.6.1211.jar
sophisticatedcore-1.20.1-1.2.23.902.jar
spark-1.10.53-forge.jar
st_cdc-1.20.1-1.02.jar
Structory_1.20.x_v1.3.5.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.18-forge-mc1.20.1.jar
supplementaries-1.20-3.1.20.jar
suppsquared-1.20-1.1.21.jar
TerraBlender-forge-1.20.1-3.0.1.10.jar
titanium-1.20.1-3.8.32.jar
TreeChop-1.20.1-forge-0.19.0-fixed.jar
trimmable_tools-forge-2.0.5.jar
voicechat-forge-1.20.1-2.5.28.jar
WI-Zoom-1.5-MC1.20.1-Forge.jar
Xaeros_Minimap_25.1.0_Forge_1.20.jar
XaerosWorldMap_1.39.4_Forge_1.20.jar
xercamusic-1.20.1-1.0.2.jar
xercapaint-1.20.1-1.0.1.jar
YungsApi-1.20-Forge-4.0.6.jar
YungsBridges-1.20-Forge-4.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar
Zeta-1.0-28.jar
zetter-1.20.1-0.21.5.jar

**Comment by Xplodin** [comment]
also getting this

**Comment by CrimsonCrips** [comment]
Update to 5.4

**Comment by IIIap** [comment]
> Update to 5.4

what? there is no 5.4 verison. even checked modrinth

**Comment by IIIap** [comment]
@CrimsonCrips

**Comment by Xplodin** [comment]
theres no changes to show for 5.4 either. I dont think 5.4 exists

**Comment by IIIap** [comment]
> theres no changes to show for 5.4 either. I dont think 5.4 exists

yeah, he just mustaked

**Comment by CrimsonCrips** [comment]
Should be fixed now in 5.3.1

**Comment by IIIap** [comment]
i still cant D:. using 5.3.1
https://logs.hosting-minecraft.pro/edebawerij
